name: Update README

on:
  workflow_dispatch: 

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        extensions: mbstring, json, curl

    - name: Install Composer Dependencies
      run: composer require guzzlehttp/guzzle

    - name: Fetch GitHub Data and Update README
      run: php .github/workflows/update_readme.php

    - name: Commit and Push Changes
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config user.name "GitHub Actions"
        git config user.email "noreply@github.com"
        git add README.md
        git commit -m "Update README dynamically"
        git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
