name: "README: WakaTime"

on:
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          COMMIT_BY_ME: "False"
          COMMIT_MESSAGE: "docs(README.md): auto update time"
          COMMIT_USERNAME: "github-actions[bot]"
          COMMIT_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_CODETIME: "False"
          SHOW_OS: "False"
          SHOW_PROJECTS: "False"
          SHOW_PROFILE_VIEWS: "True"
          SHOW_EDITORS: "False"
          SHOW_LANGUAGE: "False"
          SHOW_LINES_OF_CODE: "True"
          SHOW_COMMIT: "True"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_LOC_CHART: "False"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_TIMEZONE: "False"
          SHOW_UPDATED_DATE: "False"
